#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=1:mem=4gb

module load anaconda3/personal
#anaconda-setup

#conda create -n py27 python=2.7
#pip install emcee
#git clone https://github.com/bd-j/sedpy
#cd sedpy
#python setup.py install
#cd ..
#git clone https://github.com/cconroy20/fsps.git
#export SPS_HOME="/fsps"
#cd fsps/src
#make clean
#make all
#./simple.exe
cd $PBS_O_WORKDIR
export SPS_HOME="$HOME/p-a/fsps"

source activate py27
python prospector_alpha_mock_run.py > log
